In [90]:
import numpy as np
import time

Create array from list

In [91]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("arr_1d:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("arr_2d:", arr_2d)

arr_1d: [1 2 3 4 5]
arr_2d: [[1 2 3]
 [4 5 6]]


List vs Numpy array

In [92]:
py_list = [1, 2, 3]
print("Python list multiplication:", py_list * 2)

np_array = np.array([1, 2, 3])
print("Numpy list multiplication:", np_array * 2)

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time:", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time:", time.time() - start)


Python list multiplication: [1, 2, 3, 1, 2, 3]
Numpy list multiplication: [2 4 6]

 List operation time: 0.044463396072387695

 Numpy operation time: 0.004241943359375


Create array from scratch

In [93]:
zeros = np.zeros((3, 4))
print("zeros array \n", zeros)

ones = np.ones((3, 4))
print("ones array \n", ones)

full = np.full((2, 5), 7)
print("full array \n", full)

random = np.random.random([2, 4])
print("random array \n", random)

sequence = np.arange(0, 10, 2)
print("sequence array \n", sequence)


zeros array 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array 
 [[7 7 7 7 7]
 [7 7 7 7 7]]
random array 
 [[0.00282869 0.03726891 0.77129274 0.22152439]
 [0.10690889 0.09786274 0.39706148 0.31678746]]
sequence array 
 [0 2 4 6 8]


Vector, Matrix and Tensor

In [94]:
vector = np.array([1, 2, 3])
print("vector", vector)

matrix = np.array([
                    [1, 2, 3], 
                    [4, 5, 6]
                ])
print("matrix", matrix)

tensor = np.array([[[1, 2], [3, 4]], 
                    [[5, 6], [7, 8]]])
print("tensor", tensor)


vector [1 2 3]
matrix [[1 2 3]
 [4 5 6]]
tensor [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [95]:
arr = np.array([
                    [1, 2, 3], 
                    [4, 5, 6]
                ])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("DType", arr.dtype)


Shape (2, 3)
Dimension 2
Size 6
DType int64


Array Reshaping

In [97]:
arr = np.arange(12)
print("original array", arr)

reshaped = arr.reshape((3, 4))
print("\n reshaped array", reshaped)

flattend = reshaped.flatten()
print("\n flattend array", flattend)

## Reveled - return view instead of copy
reveled = reshaped.flatten()
print("\n reveled array", reveled)

## Transpose
transpose = reshaped.T
print("\n transpose array", transpose)


original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattend array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transpose array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
