Numpy array Operations

In [97]:
import numpy as np

In [98]:
arr = np.arange(10)
print("basic slicing", arr[2:7])
print("with step", arr[1:8:2])
print("negative indexing", arr[-3])

basic slicing [2 3 4 5 6]
with step [1 3 5 7]
negative indexing 7


In [99]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("specific element", arr_2d[1, 2])
print("entire row", arr_2d[1])
print("entire column", arr_2d[:, 1])

specific element 6
entire row [4 5 6]
entire column [2 5 8]


Sorting

In [100]:
unsorted = np.array([2, 5, 8, 7, 9, 4, 1, 3, 6])
print("unsorted arr", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 5], [6, 2]])
print("sorted 2d array by column", np.sort(arr_2d_unsorted, axis=0))


unsorted arr [1 2 3 4 5 6 7 8 9]
sorted 2d array by column [[1 1]
 [3 2]
 [6 5]]


Filter

In [101]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("even numbers", even_number)

even numbers [ 2  4  6  8 10]


Filter with mask

In [102]:
mask = numbers > 5
print("number greater than 5", numbers[mask])

number greater than 5 [ 6  7  8  9 10]


Fancy indexing vs np.where()

In [103]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("np where", numbers[where_result])

[1 3 5]
np where [ 6  7  8  9 10]


In [104]:
condition_arr = np.where(numbers > 5, True, False)
print("condition array", condition_arr)

condition array [False False False False False  True  True  True  True  True]


Adding and Remove data

In [105]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


Array Compatibility

In [106]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print(a.shape == b.shape)

True


In [107]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print("with new row", with_new_row)

new_column = np.array([[7], [8]])
with_new_column = np.hstack((original, new_column))
print("with new column", with_new_column)

with new row [[1 2]
 [3 4]
 [5 6]]
with new column [[1 2 7]
 [3 4 8]]


In [108]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
deleted = np.delete(arr, 2)
print(deleted)

[1 2 4 5 6 7 8 9]
